train:
  epochs: 1000
  batch_size: 8
  learning_rate: 1e-4
  num_workers: 0
  resume: False
  checkpoint_path: checkpoints/SSR_epoch_x_acc_x.pth
  lr: 1e-4
  patience: 3
  factor: 0.95

single_speech_recog_net:
  in_channels: 768
  in_length: 149
  classes: 8
  padding: same
  hidden_layer: 
    - 1024
    - 128
  maxpool:
    layers: 2 
    # the 2nd in_len is invalid, just as a reference.
    in_len:
      - 149
      - 64
    pool_padding_size:
      - 0
      - 0
    dilation:
      - 1
      - 1
    kernal_size:
      - 5
      - 5
    stride:
      - 2
      - 2