train:
  epochs: 1000
  batch_size: 8
  learning_rate: 1e-3
  num_workers: 0
  resume: False
  checkpoint_path: checkpoints/SSR_epoch_x_acc_x.pth
  lr: 1e-3
  patience: 3
  factor: 0.95

# BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) torch.Size([8, 768, 149])
# -----------------------------------------------------------------------------------------------------
# Conv1d(768, 512, kernel_size=(5,), stride=(1,), padding=same) torch.Size([8, 512, 149])
# -----------------------------------------------------------------------------------------------------
# PReLU(num_parameters=1) torch.Size([8, 512, 149])
# -----------------------------------------------------------------------------------------------------
# Conv1d(512, 128, kernel_size=(5,), stride=(1,), padding=same) torch.Size([8, 128, 149])
# -----------------------------------------------------------------------------------------------------
# PReLU(num_parameters=1) torch.Size([8, 128, 149])
# -----------------------------------------------------------------------------------------------------
# MaxPool1d(kernel_size=5, stride=2, padding=0, dilation=1, ceil_mode=False) torch.Size([8, 128, 73])
# -----------------------------------------------------------------------------------------------------
# Dropout(p=0.1, inplace=False) torch.Size([8, 128, 73])
# -----------------------------------------------------------------------------------------------------
# Conv1d(128, 32, kernel_size=(5,), stride=(1,), padding=same) torch.Size([8, 32, 73])
# -----------------------------------------------------------------------------------------------------
# PReLU(num_parameters=1) torch.Size([8, 32, 73])
# -----------------------------------------------------------------------------------------------------
# Conv1d(32, 1, kernel_size=(5,), stride=(1,), padding=same) torch.Size([8, 1, 73])
# -----------------------------------------------------------------------------------------------------
# PReLU(num_parameters=1) torch.Size([8, 1, 73])
# -----------------------------------------------------------------------------------------------------
# MaxPool1d(kernel_size=5, stride=2, padding=0, dilation=1, ceil_mode=False) torch.Size([8, 1, 35])
# -----------------------------------------------------------------------------------------------------
# Flatten(start_dim=1, end_dim=-1) torch.Size([8, 35])
# -----------------------------------------------------------------------------------------------------
# Linear(in_features=35, out_features=8, bias=True) torch.Size([8, 8])
# -----------------------------------------------------------------------------------------------------
# PReLU(num_parameters=1) torch.Size([8, 8])
# -----------------------------------------------------------------------------------------------------
single_speech_recog_net:
  in_channels: 768
  in_length: 149
  classes: 8
  padding: same
  hidden_layer: 
    - 512
    - 128
    - 32
    - 1
  maxpool:
    layers: 2 
    # the 2nd in_len is invalid, just as a reference.
    in_len:
      - 149
      - 64
    pool_padding_size:
      - 0
      - 0
    dilation:
      - 1
      - 1
    kernal_size:
      - 5
      - 5
    stride:
      - 2
      - 2
    